const ccb431 =
    r'''[{"id":1,"attributes":{"title":"Ó meninos, estamos reunidos","number":"431","speed":"75","firstnote":"c","lyricid":"ccblyric","firstverse":"Ó meninos, nós estamos\nReunidos ante o bom Pastor;\nAnsiosos, esperamos\nSeus conselhos de amor.","secoundverse":"Ó meninos, atendamos\nA Jesus, divino Salvador;\nPois é d`Ele que esperamos\nA virtude e o vigor.\n","thirdverse":"Ó meninos, com firmeza\nNós devemos sempre caminhar;\nÉ eterna a riqueza\nQue Jesus nos veio dar.","fourthverse":null,"chorus":"Nós estamos na presença\nDo veraz, fiel e bom Pastor,\nDesfrutando Suas bênçãos\nQue provêm do Seu amor.","final":null,"author":"Lowell Mason","createdAt":"2022-07-29T13:06:53.359Z","updatedAt":"2022-08-01T14:43:39.332Z","publishedAt":"2022-07-29T13:16:24.780Z"}}]''';
const ccb432 =
    r'''[{"id":2,"attributes": {"title":"Vem , ó divino Mestre","number":"432","speed":"96","firstnote":"c4","lyricid":"ccblyric-1","firstverse":"Senhor Jesus, bom Redentor, envia Teu poder;\nReveste os santos Teus, Senhor, de força e saber.","secoundverse":"Jesus, Cordeiro divinal, imenso é Teu amor;\nE nesse amor celestial vivemos, ó Senhor.","thirdverse":"Nas nuvens, ó Senhor Jesus, queremos Te encontrar;\nE no glorioso lar de luz, Contigo habitar.","fourthverse":null,"chorus":"Vem, ó divino Mestre,\nDá-nos saber celeste\nNós somos pequeninos, mas Tu és nosso Rei.","final":null,"author":"Charles Hutchinson","createdAt":"2022-07-29T13:15:52.874Z","updatedAt":"2022-07-29T17:48:58.194Z","publishedAt":"2022-07-29T13:28:50.137Z"}}]''';
const ccb433 =
    r'''[{"id":3,"attributes":{"title":"Na santa escola","number":"433","speed":"74","firstnote":"f","lyricid":"ccblyric-2","firstverse":"Estamos, ó meninos, na escola do Senhor;\nCantemos santos hinos a Deus, o Criador.\nNa santa escola do Mestre eterno há bem superno.","secoundverse":"Jesus, o nosso Mestre, ensina com amor\nA eterna lei celeste, que leva ao Criador.\nNa santa escola o Mestre amado e adorado.","thirdverse":"O santo Evangelho, viemos aprender;\nDe Cristo o conselho queremos atender.\nNa santa escola o Mestre ensina a sã Doutrina.","fourthverse":"O jovens e meninos, devemos conservar\nOs divinais ensinos e neles caminhar.\nNa santa escola o Mestre ouvimos e O servimos.","chorus":null,"final":null,"author":"Lowell Mason","createdAt":"2022-07-29T13:23:35.794Z","updatedAt":"2022-08-01T14:43:31.347Z","publishedAt":"2022-07-29T13:23:37.397Z"}}] ''';
const ccb434 =
    r'''[{"id":4,"attributes":{"title":"A minha alma sente paz no Senhor","number":"434","speed":"72","firstnote":"g","lyricid":"ccblyric-3","firstverse":"A minha alma sente paz no Senhor,\nPaz eternal, paz sem igual;\nPor essa paz irei ao reino de amor,\nReino celestial.","secoundverse":"Meu coração já sente o grande amor\nQue vem dos céus, que vem dos céus;\nEternamente eu serei do Senhor,\nGrande amor de Deus.","thirdverse":"Por Seu amor Jesus tornou-me feliz,\nMuito feliz, muito feliz.\nIrei com Ele ao eterno país,\nCelestial país.","fourthverse":null,"chorus":null,"final":null,"author":"George Wills Cooke","createdAt":"2022-07-29T13:25:03.387Z","updatedAt":"2022-08-01T14:43:53.176Z","publishedAt":"2022-07-29T13:25:04.463Z"}}]''';
const ccb435 =
    r'''[{"id":5,"attributes":{"title":"Ó Jesus, quanto és piedoso!","number":"435","speed":"69","firstnote":"eb","lyricid":"ccblyric-4","firstverse":"Ó Jesus, quanto és piedoso,\nInfinito é Teu amor!\nCom o Teu poder glorioso,\nFaz de mim Teu servidor;\nDedicado e fervoroso.\nQuero amar-Te, Ó Senhor. ","secoundverse":"Neste mundo sou criança,\nSó por mim não posso andar,\nMas, eu tenho a confiança\nDe no céu poder entrar;\nTua voz suave e mansa\nSempre vem me ensinar.","thirdverse":"Tenho em mim a esperança\nDe alcançar, ó Salvador,\nA sublime e eterna herança \nNo Teu reino de esplendor;\nDá-me fé e segurança,\nLuz, virtude e vigor.","fourthverse":null,"chorus":null,"final":null,"author":null,"createdAt":"2022-07-29T13:27:40.961Z","updatedAt":"2022-08-01T14:44:24.681Z","publishedAt":"2022-07-29T13:28:25.269Z"}}]''';
const ccb436 =
    r'''[{"id":6,"attributes":{"title":"Alegria sinto em servir Jesus","number":"436","speed":"78","firstnote":"d","lyricid":"ccblyric-5","firstverse":"Alegria sinto em servir Jesus,\nAlegria que no mundo não há igual;\nBem por isso sigo à eterna luz\nDa Justiça divinal.","secoundverse":"Regozijo e real consolação,\nPaz divina e celestial amor,\nMe preservam deste mundo de ilusão\nE me unem ao Senhor.","thirdverse":"Ó amados, caminhemos com Jesus,\nN’Ele temos vida eterna e salvação;\nSe aqui manifestarmos Sua luz,\nNós teremos galardão.","fourthverse":null,"chorus":"Privilégio santo, sem igual, é andar com meu Senhor,\nCaminhar em Seu amor, exaltando o Criador!\nDesejamos ver retornar dos céus\nCristo, o Rei e Salvador.","final":null,"author":"Leila Naylor Morris","createdAt":"2022-07-29T13:30:51.164Z","updatedAt":"2022-08-01T14:44:32.678Z","publishedAt":"2022-07-29T13:30:52.987Z"}}]''';
const ccb437 =
    r'''[{"id":7,"attributes":{"title":"Os meninos viram Jesus passar","number":"437","speed":"70","firstnote":"g","lyricid":"ccblyric-6","firstverse":"Os meninos viram Jesus passar;\nLogo O seguiram para proclamar:\nGloria ao que veio em nome do Senhor!\nFoi engrandecido o Redendor.","secoundverse":"Vamos exaltar a Jesus, então,\nCom os nosso lábios e o coração;\nÓ meninos, vamos ao Senhor servir\nE a lei perfeita de Deus cumprir.","thirdverse":"Eis que entre nós Jesus Cristo está;\nEle, que nos vê, nos abençoará;\nAs virtudes santas quer nos conceder,\nPara que possamos o mal vencer.","fourthverse":"Em silencio ouçamos o que dirá\nCristo, o nosso Mestre, que ensinará\nA doutrina santa que conduz aos céus;\nÓ meninos, vamos amar a Deus.","chorus":null,"final":null,"author":"Edwin Othello Excell","createdAt":"2022-07-29T13:32:40.369Z","updatedAt":"2022-08-01T14:44:37.738Z","publishedAt":"2022-07-29T13:32:41.620Z"}}]''';
const ccb438 =
    r'''[{"id":8,"attributes":{"title":"Oh! que amor celeste!","number":"438","speed":"♪ = 119","firstnote":"bb","lyricid":"ccblyric-7","firstverse":"Bem perto está dos Seus fiéis\nJesus, o grande Mestre;\nJamais os deixa o Rei dos reis;\nOh! que amor celeste!","secoundverse":"Jesus o nosso Redentor,\nDo alto nos reveste;\nNas provas, lutas ou na dor\nPresente está o Mestre.","thirdverse":"Na nossa peregrinação,\nÉ Cristo quem nos guia;\nEstende sempre a Tua mão,\nNos guarda noite e dia.","fourthverse":null,"chorus":"Perto está o Salvador\nDos que O têm por seu Pastor;\nNão nos deixa o Redentor;\nOh! que amor celeste!","final":null,"author":"John Hart Stockton","createdAt":"2022-07-29T13:36:46.796Z","updatedAt":"2022-08-01T14:44:42.929Z","publishedAt":"2022-07-29T13:36:47.929Z"}}]''';
const ccb439 =
    r'''[{"id":9,"attributes":{"title":"Somos jovens","number":"439","speed":"79","firstnote":"d","lyricid":"ccblyric-8","firstverse":"Somos jovens, mas devemos sempre andar\nNo temor do Criador,\nO Modelo santo vamos imitar:\nJesus Cristo, Salvador.","secoundverse":"Cristo é a Luz divina para nós,\nVemos n’Ele a perfeição;\nOuviremos, sempre atentos, Sua voz,\nQue consola o coração.","thirdverse":"Se seguirmos sempre firmes ao Senhor,\nCom sincero coração,\nEle nos dará no reino de esplendor,\nO glorioso galardão.","fourthverse":null,"chorus":"Em amor, com vigor,\nNos, jovens, vamos caminhar!\nMostrando a luz do Salvador\nE honrando ao Criador.","final":null,"author":"James McGranahan","createdAt":"2022-07-29T13:39:20.788Z","updatedAt":"2022-08-01T14:44:56.593Z","publishedAt":"2022-07-29T13:39:21.712Z"}}]''';
const ccb440 =
    r'''[{"id":10,"attributes":{"title":"Lembra-te do teu Criador!","number":"440","speed":"71","firstnote":"c","lyricid":"ccblyric-9","firstverse":"Nos dias da tua peregrinação,\nUsa o tempo servindo ao Senhor\nE, com alegria, cumpre a missão;\nLembra-te do Criador!","secoundverse":"Os preditos dias logo hão de vir,\nServe, pois, a Deus, o Formador;\n“Vinde, ó benditos” tu irás ouvir;\nDe Jesus, teu Redentor.","thirdverse":"Mesmo tendo, neste mundo, muitos bens\nE a vida cheia de vigor,\nÉ maior a herança que, na glória tens;\nCom o santo Criador.","fourthverse":null,"chorus":"Debaixo do Sol tudo é vaidade,\nRecorre a Deus, o Formador;\nNos breves dias da mocidade,\nNão te esqueças do Senhor!\n","final":null,"author":"Isaac Hickman Meredith","createdAt":"2022-07-29T13:40:54.902Z","updatedAt":"2022-08-01T14:45:01.461Z","publishedAt":"2022-07-29T13:40:55.730Z"}}]''';
const ccb441 =
    r'''[{"id":12,"attributes":{"title":"Eu sou um cordeirinho","number":"441","speed":"60","firstnote":"d","lyricid":"ccblyric-10","firstverse":"Eu sou um cordeirinho, Jesus é o meu Pastor;\nDesfruto Seu carinho e Seu sublime amor;\nNasci no Seu rebanho, por graça divinal,\nNão sigo a voz do estranho, mas só a Paternal.","secoundverse":"Eu sou um cordeirinho, Jesus é o meu Pastor,\nSou um feliz menino nos braços do Senhor;\nA Sua voz conheço, também o Seu querer;\nA Ele obedeço, disposto e com prazer.","thirdverse":"Sozinho no deserto, jamais eu posso andar;\nJesus está bem perto a fim de me guardar;\nÉ grande o cuidado que Ele tem por mim,\nO meu Pastor amado me guia até o fim.","fourthverse":null,"chorus":null,"final":null,"author":null,"createdAt":"2022-08-01T14:43:18.773Z","updatedAt":"2022-08-01T14:46:18.124Z","publishedAt":"2022-08-01T14:45:11.890Z"}}]''';
const ccb442 =
    r'''[{"id":13,"attributes":{"title":"Bênçãos, bênçãos Deus derramará","number":"442","speed":"70","firstnote":"eb","lyricid":"ccblyric-11","firstverse":"Bênçãos como chuva, se derramarão\nSobre aquele que a Deus servir;\nE dos céus as portas não se fecharão;\nBens celestes poderá fruir.","secoundverse":"Se obedeceres ao teu Criador,\nTu serás benditos do Senhor\nO Seu forte braço Ele estenderá,\nE em teu favor trabalhará.","thirdverse":"O que Deus te pede, deves tu fazer\nE somente a Ele obedecer,\nPois Deus é contigo, te ajudará\nE, dos céus, te abençoará.","fourthverse":null,"chorus":"Bênçãos, bênçãos Deus derramará,\nBênçãos que no mundo iguais não há;\nEle aqui te dá as bênçãos temporais,\nE, por fim, no céu, as eternais.","final":null,"author":"George Frederick Root","createdAt":"2022-08-01T14:48:14.126Z","updatedAt":"2022-08-01T14:48:15.177Z","publishedAt":"2022-08-01T14:48:15.170Z"}}]''';
const ccb443 =
    r'''[{"id":14,"attributes":{"title":"Ó meninos, Deus vos convida","number":"443","speed":"74","firstnote":"f","lyricid":"ccblyric-12","firstverse":"Ó meninos, Deus vos convida\nPara a grande festa nos céus;\nRegozijo eterno e vida\nAchareis no reino de Deus.\nGrande glória la vos aguarda,\nBenção que aqui não tereis;\nAtendei, pois Cristo não tarda;\nBrevemente vós O vereis.","secoundverse":"Deslumbrante é a beleza\nDas moradas do Criador\nQue reserva essa riqueza\nAos remidos por Seu amor.\nVós vereis na glória celeste,\nGlória onde é tudo esplendor.\nTodos quantos seguem ao Mestre,\nJesus Cristo, nosso Senhor.","thirdverse":"Tão somente santificai-vos\nPela força do nosso Deus;\nDe justiça sempre adornai-vos,\nPara a grande festa nos céus.\nTodos juntos nós subiremos\nCom Jesus, ao Pai celestial;\nDiante d’Ele entoaremos\nHinos de louvor eternal.","fourthverse":null,"chorus":null,"final":null,"author":"John Zundel","createdAt":"2022-08-01T14:49:39.045Z","updatedAt":"2022-08-01T14:49:45.949Z","publishedAt":"2022-08-01T14:49:40.529Z"}}]''';
const ccb444 =
    r'''[{"id":15,"attributes":{"title":"Ó meninos, exaltemos","number":"444","speed":"61","firstnote":"a","lyricid":"ccblyric-13","firstverse":"Ó meninos, exaltemos a Jesus, o Salvador;\nSempre alegres, seguiremos ao amado e bom Pastor,\nPois na boca das crianças é perfeito o louvor\nA Jesus, nossa Esperança e a Deus, o Criador.","secoundverse":"Nesta terra proclamamos que Jesus é o Salvador;\nCom fervor, manifestamos Seu sublime e grande amor;\nQuando juntos estivermos na cidade de esplendor,\nTodos nós contemplaremos nosso amado Redentor.","thirdverse":null,"fourthverse":null,"chorus":null,"final":null,"author":null,"createdAt":"2022-08-01T14:50:43.218Z","updatedAt":"2022-08-01T14:50:44.707Z","publishedAt":"2022-08-01T14:50:44.704Z"}}]''';
const ccb445 =
    r'''[{"id":16,"attributes":{"title":"Ajuntemos um tesouro eterno","number":"445","speed":"82","firstnote":"f","lyricid":"ccblyric-14","firstverse":"Ajuntemos, ó meninos nosso bom tesouro lá nos céus de amor.\nOnde habita nosso Mestre e o Pai eterno nosso Criador.","secoundverse":"Ricos das eternas bênçãos e dos dons celestes que nos vêm de Deus,\nCaminhemos nas veredas da justiça eterna, que nos leva aos céus.","thirdverse":"Ao sairmos deste mundo, tudo deixaremos, tudo findará.\nO tesouro ajuntado na eterna glória sempre durará.","fourthverse":null,"chorus":"Ajuntemos um tesouro eterno\nOnde habita nosso Deus superno.\nNos Céus os bens jamais se acabarão","final":null,"author":"Henry Tucker","createdAt":"2022-08-01T14:52:20.026Z","updatedAt":"2022-08-01T14:52:21.471Z","publishedAt":"2022-08-01T14:52:21.463Z"}}]''';
const ccb446 =
    r'''[{"id":17,"attributes":{"title":"Vós, ó jovens do Senhor","number":"446","speed":"72","firstnote":"g","lyricid":"ccblyric-15","firstverse":"Vós, ó jovens do Senhor, dai-lhe honra e louvor,\nEsforçai-vos por servir ao Rei do reis;\nRevesti-vos, pois, de fé e do Seu imenso amor\nE o que d’Ele precisardes vós tereis,","secoundverse":"Sois remidos, ó irmãos, sois amados de Jesus,\nE sois fortes para suplantar o mal;\nPelo bom Consolador vós tereis virtude e luz;\nSim, crescei na estatura divinal.","thirdverse":"Se vier o tentador com ofertas vos tentar,\nIncitando-vos a males cometer,\nRecorrei ao Salvador, Ele vos virá livrar;\nVós, ó jovens, não deveis jamais ceder","fourthverse":null,"chorus":"Vós, ó jovens do Senhor, oh! amai-O com fervor,\nO que Ele vos mandar, procurai executar;\nMorareis com Deus em Seu lar;\nDiligentes sede vós, Ele não vos deixa sós,\nMas convosco estará e as forças vos dará,\nPois a graça n’Ele está.","final":null,"author":"Charles Hutchinson","createdAt":"2022-08-01T14:53:47.964Z","updatedAt":"2022-08-01T14:53:48.938Z","publishedAt":"2022-08-01T14:53:48.933Z"}}]''';
const ccb447 =
    r'''[{"id":18,"attributes":{"title":"Brilha mais e mais","number":"447","speed":"67","firstnote":"eb","lyricid":"ccblyric-16","firstverse":"Estás na senda divinal que te faz brilhar;\nO teu lugar celestial, Deus irá te dar.","secoundverse":"É teu desejo receber dons do teu Senhor?\nVerás que há no Seu saber santo resplendor.","thirdverse":"Repouso eterno há nos céus junto ao bom Jesus;\nPor fim verás o grande Deus onde habita a luz.","fourthverse":null,"chorus":"Brilha mais e mais,\nCaminha com Jesus;\nTerás em ti a Sua luz,\nBrilhando sempre mais.","final":null,"author":"William James Kirckpatrick","createdAt":"2022-08-01T14:55:32.282Z","updatedAt":"2022-08-01T14:55:33.440Z","publishedAt":"2022-08-01T14:55:33.436Z"}}]''';
const ccb448 =
    r'''[{"id":19,"attributes":{"title":"Sou criança, Senhor","number":"448","speed":"♪ = 110","firstnote":"d","lyricid":"ccblyric-17","firstverse":"Sou criança, Senhor, mas desejo seguir\nOs Teus passos, na senda de luz;\nTeus conselhos de amor eu almejo ouvir\nAos Teus pés, ó amável Jesus.","secoundverse":"Sou criança, Senhor, mas fiel quero ser\nÀ Palavra que livra do mal;\nCom amor e fervor eu desejo crescer\nNas virtudes da vida eternal.","thirdverse":"Sou criança, Senhor, mas zeloso do bem,\nTuas bençãos estão sobre mim;\nCaminhando em amor, em justiça também,\nEu serei coroado ao fim.","fourthverse":null,"chorus":"Sou criança, mas crente em Jesus\nMeu amado e divino Pastor,\nQue em mim faz brilhar Sua luz,\nConduzindo-me ao reino de amor.","final":null,"author":"George Bennard","createdAt":"2022-08-01T14:58:22.002Z","updatedAt":"2022-08-01T14:58:22.963Z","publishedAt":"2022-08-01T14:58:22.961Z"}}]''';
const ccb449 =
    r'''[{"id":20,"attributes":{"title":"O meu nome no céu escreveste, Senhor","number":"449","speed":"79","firstnote":"eb","lyricid":"ccblyric-18","firstverse":"As riquezas celestes eu almejo, Senhor,\nOs tesouros da terra tem pequeno valor.\nCom fervor eu Te rogo, ó eterno Deus meu,\nQue conserves escrito o meu nome no céu.","secoundverse":"Que ventura sublime! que tesouro sem par!\nPois verei Teu semblante, ouvirei Teu falar;\nO meu nome não risques, eu imploro Senhor,\nEntre os Teus escolhidos quero estar, Criador.","thirdverse":"Tu me predestinaste para ser filho Teu,\nPara ser Teu herdeiro, com os santos, no céu;\nComo posso pagar-Te essa grande mercê?!\nPois em mim colocaste a esperança e a fé.","fourthverse":null,"chorus":"O meu nome no céu escreveste, Senhor\nNo Teu livro da vida, por Teu grande amor.\n","final":null,"author":"Frank Marion Davis","createdAt":"2022-08-01T14:59:59.091Z","updatedAt":"2022-08-01T15:00:00.376Z","publishedAt":"2022-08-01T15:00:00.370Z"}}]''';
const ccb450 =
    r'''[{"id":21,"attributes":{"title":"Vamos, queridos, escolher a boa parte","number":"450","speed":"75","firstnote":"eb","lyricid":"ccblyric-19","firstverse":"Vamos, queridos, escolher\nA boa parte para nós,\nSempre ouvindo, com prazer,\nDe Jesus Cristo, a doce voz.","secoundverse":"Não há no mundo nada igual\nAo regozijo de estar\nAos pés do Mestre divinal,\nA Quem devemos sempre amar.","thirdverse":"A boa parte que nos dá\nCristo Jesus, o Redentor,\nNada, de nós a tomará,\nSe a guardarmos com amor.","fourthverse":null,"chorus":"Grande bem, sem igual,\nÉ estar diante do Senhor\nSua voz divinal\nNos ensina com sublime amor.","final":null,"author":"William Augustine Ogden","createdAt":"2022-08-01T15:01:39.000Z","updatedAt":"2022-08-01T15:01:40.030Z","publishedAt":"2022-08-01T15:01:40.025Z"}}]''';
const ccb451 =
    r'''[{"id":22,"attributes":{"title":"Jamais esquecerei Tua mercê","number":"451","speed":"♪ = 118","firstnote":"d","lyricid":"ccblyric-20","firstverse":"Não poderei jamais esquecer\nTua mercê, Senhor;\nDeste aos pequenos de conhecer\nTua grandeza e amor.","secoundverse":"Oh! que tesouro de esplendor\nTu me darás nos céus;\nNão há herança de igual valor\nPara Teus filhos, ó Deus.","thirdverse":"Se eu andar sempre em Teu temor,\nAo fim eu entrarei\nNo reino eterno de esplendor,\nOnde o repouso terei.","fourthverse":null,"chorus":"Jamais esquecerei\nTua mercê, ó Criador;\nPor Cristo alcançarei\nGrande tesouro de amor.","final":null,"author":"William Stillman Martin","createdAt":"2022-08-01T17:58:10.873Z","updatedAt":"2022-08-01T17:58:12.069Z","publishedAt":"2022-08-01T17:58:12.064Z"}}]''';
const ccb452 =
    r'''[{"id":23,"attributes":{"title":"Jesus, ó divinal Pastor","number":"452","speed":"71","firstnote":"eb","lyricid":"ccblyric-21","firstverse":"Jesus, ó divinal Pastor, O Teu rebanho quer Te ouvir;\nCom Teu Espírito, ó Senhor, vem este culto presidir.\nNós somos todos cordeirinhos do Teu aprisco, ó Redentor;\nSó Tu nos tratas com carinho, Ó glorioso Salvador.","secoundverse":"Jesus, glorioso e fiel, em Ti está o nosso bem;\nTu és o nosso Emanuel, és Quem, na graça, nos sustém.\nAqui estamos reunidos ao Teu redor, fiel Senhor,\nPois, onde estão os Teus remidos, também estás, ó bom Pastor.","thirdverse":"Nós Te seguimos, Redentor, Pois conhecemos Tua voz,\nVoz que nos fala com amor, dizendo: “Não vos deixo sós.”\nA pastos sempre verdejantes Tu nos conduzes, ó Senhor.\nPor isso estamos confiantes, sentindo a Tua paz e amor.","fourthverse":null,"chorus":null,"final":null,"author":"Phoebe Palmer Knapp ","createdAt":"2022-08-01T18:00:16.023Z","updatedAt":"2022-08-01T18:00:17.200Z","publishedAt":"2022-08-01T18:00:17.194Z"}}]''';
const ccb453 =
    r'''[{"id":24,"attributes":{"title":"Consagrados sejamos a Deus","number":"453","speed":"102","firstnote":"f","lyricid":"ccblyric-22","firstverse":"Se quisermos, irmãos, do Senhor receber\nAs virtudes da vida eternal,\nSeja a nossa afeição e o nosso prazer\nEm Jesus e na lei celestial.","secoundverse":"Se quisermos, irmãos, ser benditos de Deus,\nAdoremo-Lo com devoção;\nSeus preceitos de amor Ele envia dos céus,\nSeja ele a nossa Porção.","thirdverse":"Se honrarmos a Deus, Ele nos honrará,\nNesta terra e na pátria eternal;\nUm diadema nos céus, Ele concederá,\nAo Entramos no lar divinal.","fourthverse":null,"chorus":"Consagrados sejamos a Deus, Criador\nE Ele de nós, Se agradará\nAbrirá Sua mão e, com grande amor,\nBoas dádivas nos mandará.\n","final":null,"author":"Elisha Albright Hoffman","createdAt":"2022-08-01T18:02:49.423Z","updatedAt":"2022-08-01T18:02:51.007Z","publishedAt":"2022-08-01T18:02:51.002Z"}}]''';
const ccb454 =
    r'''[{"id":25,"attributes":{"title":"Cidadão dos céus","number":"454","speed":"♪ = 115","firstnote":"b","lyricid":"ccblyric-23","firstverse":"O Deus bendito, sou pequenino,\nMas já caminho pelo Teu ensino;\nSou neste mundo um peregrino,\nJá me fizeste cidadão dos céus.","secoundverse":"Vivo alegre, em paz Te sigo,\nNada receio, pois estou Contigo;\nNeste deserto, em Ti me abrigo;\nJá me fizeste cidadão dos céus.","thirdverse":"És minha Força e Segurança,\nÉs meu Apoio, minha Esperança,\nÉs minha Vida e Confiança;\nJá me fizeste cidadão dos céus.","fourthverse":null,"chorus":null,"final":null,"author":"Lowell Mason","createdAt":"2022-08-01T18:05:01.468Z","updatedAt":"2022-08-01T18:05:10.494Z","publishedAt":"2022-08-01T18:05:10.488Z"}}]''';
const ccb455 =
    r'''[{"id":26,"attributes":{"title":"Quão ditoso é caminhar com Jesus!","number":"455","speed":"74","firstnote":"ab","lyricid":"ccblyric-24","firstverse":"Alegremente seguimos os passos\nDo nosso bom Salvador, nosso Rei,\nPois acolheu-nos em Seus santos braços,\nDesde crianças nos fez Sua grei.","secoundverse":"Nesta jornada unidos devemos,\nSempre dispostos, a Cristo seguir;\nE no Seu Nome, vitória teremos,\nDesfrutaremos os bens do porvir.","thirdverse":"O Salvador nos conduz nesta vida,\nPara fazer-nos morar lá nos céus;\nE nessa pátria, gloriosa e querida,\nContemplaremos a face de Deus.","fourthverse":null,"chorus":"Quão ditoso é caminhar com Jesus, ó meninos!\nSomos Sua grei, Ele é o bom Pastor;\nSeguimos, com amor, os preciosos ensinos\nDe Deus, Criador.","final":null,"author":"William James Kirckpatrick","createdAt":"2022-08-01T18:06:42.504Z","updatedAt":"2022-08-01T18:06:43.257Z","publishedAt":"2022-08-01T18:06:43.253Z"}}]''';
const ccb456 =
    r'''[{"id":27,"attributes":{"title":"Somos jóias preciosas","number":"456","speed":"70","firstnote":"eb","lyricid":"ccblyric-25","firstverse":"Ao voltar, com grande glória, Jesus Cristo, o Redentor,\nLevará as Suas jóias para o reino de esplendor.","secoundverse":"Destas jóias preciosas Cristo sempre cuidará;\nSempre belas e brilhantes Ele as conservará.","thirdverse":"Revestidos de pureza caminhando em amor,\nAguardemos, bem atentos, o retorno do Senhor.","fourthverse":null,"chorus":"Somos jóias preciosas\nDo tesouro do Senhor;\nSomos belas, mui formosas,\nSomos jóias de valor.","final":null,"author":"George Frederick Root","createdAt":"2022-08-01T18:08:05.270Z","updatedAt":"2022-08-01T18:08:06.507Z","publishedAt":"2022-08-01T18:08:06.503Z"}}]''';
const ccb457 =
    r'''[{"id":28,"attributes":{"title":"Comigo está Jesus","number":"457","speed":"♪ = 124","firstnote":"e","lyricid":"ccblyric-26","firstverse":"Comigo está Jesus, meu bom Mestre e Salvador,\nMe guia com a luz, pelo seu imenso amor;\nMistérios celestiais Jesus revelará;\nNo Seu bom caminho andar me fará.","secoundverse":"Quem me separará do sublime amor de Deus?\nQuem me condenará? Pois Jesus defende os Seus.\nUnido ao Senhor por celestial amor,\nCaminho avante com fé e valor.","thirdverse":"Das sendas celestiais eu não me afastarei;\nPois amo sempre mais a doutrina do meu Rei;\nJesus me guiará e forças me dará.\nO Mestre amado comigo está.","fourthverse":null,"chorus":null,"final":"Estou com Jesus, meu Senhor; vou vencer!\nJesus ama os Seus e as coisas de Deus lhes faz saber,\nA nada aqui temerei, pois eu bem sei\nQue tudo está sob as ordens do meu Rei.","author":null,"createdAt":"2022-08-01T18:10:07.034Z","updatedAt":"2022-08-01T18:10:08.279Z","publishedAt":"2022-08-01T18:10:08.275Z"}}]''';
const ccb458 =
    r'''[{"id":29,"attributes":{"title":"Cristo me ama","number":"458","speed":"66","firstnote":"eb","lyricid":"ccblyric-27","firstverse":"Sou amado por Jesus,\nA palavra assim me diz;\nEle é a minha Luz\nE me leva ao Seu país.","secoundverse":"Sou amado por Jesus,\nPois por mim na cruz morreu;\nEle agora me conduz\nPara o lar que prometeu.","thirdverse":"Sou amado por Jesus,\nPois comigo sempre está;\nSeu conselho em mim produz\nForça que me susterá.","fourthverse":null,"chorus":"Cristo me ama,\nSei que me ama,\nMuito me ama,\nEm Cristo sou feliz.","final":null,"author":"William Batchelder Bradbury","createdAt":"2022-08-01T18:13:09.077Z","updatedAt":"2022-08-01T18:13:10.189Z","publishedAt":"2022-08-01T18:13:10.186Z"}}]''';
const ccb459 =
    r'''[{"id":30,"attributes":{"title":"Vamos nos preparar!","number":"459","speed":"♪ = 128","firstnote":"e","lyricid":"ccblyric-28","firstverse":"Cristo Jesus breve voltará, vamos nos preparar!\nEle à glória nos levará, para nos coroar!\nReceberá os remidos Seus\nPara habitarem no céu dos céus,\nJunto aos anjos e a Deus - Vamos nos preparar!","secoundverse":"Não cederemos a tentação; vamos, com fé, lutar;\nRejeitaremos a ilusão, para não vacilar,\nQuando voltar cristo, o salvador,\nVitorioso com esplendor,\nEncontrará em nós valor, Vamos nos preparar!","thirdverse":null,"fourthverse":null,"chorus":null,"final":"Glória! Glória a Cristo, o Rei dos reis!\nGlória! Glória! cantam os Seus fiéis;\nGlória! Glória! na terra e nos céus,\nGlória! Glória ao poderoso Deus!","author":"Leila Naylor Morris","createdAt":"2022-08-01T18:15:57.024Z","updatedAt":"2022-08-01T18:15:58.276Z","publishedAt":"2022-08-01T18:15:58.270Z"}}]''';
const ccb460 =
    r'''[{"id":31,"attributes":{"title":"Vamos todos juntos cantar","number":"460","speed":"78","firstnote":"f","lyricid":"ccblyric-29","firstverse":"Vamos todos juntos cantar:\nGlória a Jesus! Glória a Jesus!\nVamos todos juntos louvar\nAo Senhor Jesus!\nEle é a nossa Paz, Ele é a nossa Luz;\nExaltemos, com devoção,\nAo Senhor Jesus!","secoundverse":"Somos salvos por Seu amor;\nGlória a Jesus! Glória a Jesus!\nSuportou por nós grande dor\nO Senhor Jesus.\nQuem nos dá perdão, Quem ao céu conduz\nÉ o santo Filho de Deus,\nO Senhor Jesus.","thirdverse":"Mui felizes somos então;\nGlória a Jesus! Glória a Jesus!\nRecebemos consolação\nDo Senhor Jesus.\nNo Seu lar de amor, no Seu lar de luz,\nNovo hino vamos cantar\nAo Senhor Jesus.","fourthverse":null,"chorus":null,"final":null,"author":"Harry Dedley Clarke","createdAt":"2022-08-01T18:17:28.360Z","updatedAt":"2022-08-01T18:17:29.603Z","publishedAt":"2022-08-01T18:17:29.597Z"}}]''';
const ccb461 =
    r'''[{"id":32,"attributes":{"title":"Abrigado em Jesus","number":"461","speed":"67","firstnote":"e","lyricid":"ccblyric-30","firstverse":"Abrigado em Jesus, lutas não mais temereis;\nEle é a minha Luz e por ela andarei.","secoundverse":"Abrigado em Jesus, posso sempre caminhar\nPela senda que conduz ao sublime, eterno lar.","thirdverse":"Abrigado em Jesus, mesmo quando em aflição;\nSinto em mim a Sua Luz, que ilumina o coração.","fourthverse":null,"chorus":"A Jesus, meu Senhor, minha vida consagrei;\nEm meu bom Redentor, forte abrigo encontrei.","final":null,"author":"James David Vaughan","createdAt":"2022-08-01T18:19:26.168Z","updatedAt":"2022-08-01T18:19:27.192Z","publishedAt":"2022-08-01T18:19:27.173Z"}}]''';
const ccb462 =
    r'''[{"id":33,"attributes":{"title":"Gloriosa é a história","number":"462","speed":"77","firstnote":"g","lyricid":"ccblyric-31","firstverse":"Gloriosa é a historia\nQue nos fala de Jesus;\nSendo Rei, Senhor da glória,\nPadeceu por nós na cruz.\n","secoundverse":"Veio ao mundo sem pecado,\nO divino Salvador;\nConservou-Se imaculado\nE venceu o tentador.","thirdverse":"O Senhor, crucificado,\nNo madeiro expirou;\nTudo estava consumado;\nSeu espírito entregou.","fourthverse":"Foi Jesus glorificado,\nPois da morte retornou;\nPara o céu foi elevado\nE Deus Pai O exaltou.","chorus":"Quão gloriosa é a história\nDe Jesus, o Salvador,\nQue alcançou final vitória\nE no céu é Intercessor.","final":null,"author":"Peter Philip Bilhorn","createdAt":"2022-08-01T18:21:17.887Z","updatedAt":"2022-08-01T18:21:19.165Z","publishedAt":"2022-08-01T18:21:19.161Z"}}]''';
const ccb463 =
    r'''[{"id":34,"attributes":{"title":"Mocidade! Vamos combater!","number":"463","speed":"77","firstnote":"eb","lyricid":"ccblyric-32","firstverse":"Com valor, ó jovens, santos do Senhor,\nVamos proclamar que Cristo é o Salvador;\nOs que n’Ele crerem, certo alcançarão\nVida eterna e perdão.","secoundverse":"Sempre avante, ó jovens, vamos com valor,\nCombater, por fé, o astuto tentador;\nCristo, com Seu braço, nos sustentará\nE vitória nos dará.","thirdverse":"Bem-aventurados somos no Senhor,\nTemos alcançado a unção do Criador,\nPela qual sentimos paz e comunhão,\nPara eterna salvação.","fourthverse":null,"chorus":"Mocidade! Vamos combater!\nValorosos somos por Jesus!\nVenceremos pelo Seu poder,\nManifestaremos Sua luz.","final":null,"author":"Grant Colfax Tullar","createdAt":"2022-08-01T18:24:00.901Z","updatedAt":"2022-08-01T18:24:06.495Z","publishedAt":"2022-08-01T18:24:06.490Z"}}]''';
const ccb464 =
    r'''[{"id":35,"attributes":{"title":"Reunidos nós estamos","number":"464","speed":"66","firstnote":"g","lyricid":"ccblyric-33","firstverse":"Reunidos nós estamos aos Teus pés, ó Criador,\nAnsiosos esperamos tuas bênçãos, Teu favor,\nGlorificado seja sempre Teu santo Nome, ó Senhor,\nE teu reino anunciado para todo o pecador.","secoundverse":"Ó Senhor, só Tu conheces nossa mente e coração,\nElevamos nossas preces com sincera devoção.\nNós invocamos o Teu Nome e desejamos Te honrar,\nDá-nos força, Pai eterno para Te glorificar.","thirdverse":"Faz que nós consideremos que presente estás, ó Deus,\nPara que nos alegremos nos fieis conselhos Teus;\nTua palavra de virtude nós esperamos, ó Senhor,\nNEla está a plenitude do Teu santo e imenso amor.","fourthverse":null,"chorus":null,"final":null,"author":"John Wyeth","createdAt":"2022-08-01T18:25:35.590Z","updatedAt":"2022-08-01T18:25:37.362Z","publishedAt":"2022-08-01T18:25:37.357Z"}}]''';
const ccb465 =
    r'''[{"id":36,"attributes":{"title":"Deus tem por nós imenso amor","number":"465","speed":"72","firstnote":"d","lyricid":"ccblyric-34","firstverse":"Nesta hora reunidos nós estamos ante Deus\nE em nome de Jesus, o Salvador;\nQuer-nos todos reverentes nosso Pai que está nos céus;\nDeus tem por nós imenso amor.","secoundverse":"Como filhos reverentes que obedecem a seu pai,\nAtendamos ao sublime Criador;\nLá no céu os Seus tesouros conceder-nos Ele vai;\nDeus tem por nós imenso amor.","thirdverse":"Se andamos pela senda da justiça e da luz,\nTem prazer em nossas almas, o Senhor;\nSe aqui nós imitamos o Modelo, que é Jesus,\nDeus tem por nós imenso amor. ","fourthverse":null,"chorus":null,"final":"Ao eterno Pai celeste honra e glória vamos dar\nE, atentos, Seus conselhos escutar;\nSuas bênçãos gloriosas nos dará o Criador,\nDeus tem por nós imenso amor.","author":null,"createdAt":"2022-08-01T18:27:05.938Z","updatedAt":"2022-08-01T18:27:10.112Z","publishedAt":"2022-08-01T18:27:06.735Z"}}]''';
const ccb466 =
    r'''[{"id":37,"attributes":{"title":"A criança consagrada","number":"466","speed":"72","firstnote":"g","lyricid":"ccblyric-35","firstverse":"A criança consagrada \nA Jesus, meu Salvador,\nÉ, por Ele, ensinada\nA servir ao Criador.","secoundverse":"Cristo chama os pequeninos\nCom ternura e amor,\nQuando a Deus entoam hinos\nÉ aceitou seu louvor.","thirdverse":"Cristo é a Luz divina\nEnviada lá dos céus;\nEle trouxe a sã doutrina\nQue conduz, por fé, a Deus.","fourthverse":null,"chorus":null,"final":null,"author":"Edwin Othello Excell","createdAt":"2022-08-01T18:28:19.195Z","updatedAt":"2022-08-01T18:28:20.439Z","publishedAt":"2022-08-01T18:28:20.436Z"}}]''';
const ccb467 =
    r'''[{"id":38,"attributes":{"title":"Vamos com Jesus","number":"467","speed":"72","firstnote":"bb2","lyricid":"ccblyric-36","firstverse":"Sigamos, com fervor, Jesus, o Salvador,\nQue por amor nos livrou da condenação;\nË Ele o nosso Rei, nós somos Sua grei,\nQue irá, no céu, receber o grande galardão.","secoundverse":"Oh! Vamos combater e, pela fé, vencer\nO tentador que nos quer para o mal levar;\nSigamos ao Senhor com todo fervor;\nSó Ele tem armas que nos fazem triunfar.","thirdverse":"Mistérios celestiais, riquezas eternais,\nJesus, o Rei, por amor nos desvendará;\nFelizes, pois, nos céus, seremos junto a Deus\nNaquele lar nosso coração jubilará.","fourthverse":null,"chorus":"Vamos com Jesus, Ele nos conduz\nAo Seu reino de amor;\nMarchemos com valor à pátria celestial\nO nosso Rei nos dará a glória eternal.","final":null,"author":"Flora Hamilton Cassel","createdAt":"2022-08-01T18:29:53.440Z","updatedAt":"2022-08-01T18:29:54.268Z","publishedAt":"2022-08-01T18:29:54.263Z"}}]''';
const ccb468 =
    r'''[{"id":39,"attributes":{"title":"Toda a criança...","number":"468","speed":"72","firstnote":"c4","lyricid":"ccblyric-37","firstverse":"Toda a criança que, com fé e amor,\nServe ao Deus vivente, santo Criador,\nCresce na justiça e na retidão,\nCom a lei de Cristo em seu coração.","secoundverse":"Toda a criança deve conhecer\nQuanto é glorioso junto a Deus viver.\nGrande alegria lhe dará Jesus;\nEle a protege, Ele a conduz.","thirdverse":"Deus, o Pai eterno, ouve a oração\nQue toda a criança faz com devoção.\nCristo, com Seu braço, firme a sustém,\nPara que alcance o eterno bem.","fourthverse":null,"chorus":null,"final":null,"author":null,"createdAt":"2022-08-01T18:30:46.813Z","updatedAt":"2022-08-01T18:30:50.868Z","publishedAt":"2022-08-01T18:30:50.864Z"}}]''';
